### ISSUE TITLE
Brak instrukcji Lab3

### ISSUE THREAD

**Issue by Kiedro** [AdamKamizelich/ViessmannUniversityCooperation#2]
Czy jest możliwość opublikowania instrukcji do lab3?

**Comment by BrightShadow** [comment]
Witam, przekażę dalej. Wybacz to pewnie jakieś uchybienie.

**Comment by BrightShadow** [comment]
WSzystkie instrukcje są w branchu MASTER w folderze [Docs](https://github.com/AdamKamizelich/ViessmannUniversityCooperation/tree/master/Docs)

**Comment by Kiedro** [comment]
Dzięki!
